### PR TITLE
added popup in item and items

### PR DESCRIPTION
**Pull request by krishnaglodha**
Added popups for leaflet map as per issue #59

### CODE REVIEW

**Comment by krishnaglodha** [comment]
Item
Screenshot 2023-07-15 at 1 32 25 PM


Items
Screenshot 2023-07-15 at 1 32 50 PM

**Review by vincentsarago — APPROVED** [review]

**Comment by vincentsarago** [comment]
@krishnaglodha that's awesome/

Could you please add a line in the changelog 🙏

**Comment by krishnaglodha** [comment]
> @krishnaglodha that's awesome/
> 
> Could you please add a line in the changelog 🙏

@vincentsarago , can you please share me link for changelog file please ?

**Comment by vincentsarago** [comment]
https://github.com/developmentseed/tipg/blob/main/CHANGES.md

**Review by vincentsarago — APPROVED** [review]

**Pull request merged**
